[project]
name = "battlefield2"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "redis>=5.2.0",
    "rq-dashboard>=0.8.2.2",
    "rq>=2.0.0",
    "sh>=2.1.0",
]
